- hosts: all
  tasks:
  # 1. Yum install htttpd
  - name: Install Apache
    package:
      name: "{{ package }}"
      state: latest

  # 2.  Systemctl start/enable httpd
  - name: Start Apache
    service:
      name: "{{ package }}"
      state: started
      enabled: yes

  # 3. Install wget unzip
  - name: Install wget and unzip
    package:
      name: "{{ packages }}"
    vars:
      packages:
      - wget
      - unzip

  # 5. unzip koppee.zip
  - name: Download and extract Template
    unarchive:
      src: https://www.free-css.com/assets/files/free-css-templates/download/page281/koppee.zip
      dest: /tmp/
      remote_src: yes

  # 6. Copy file to /var/www/html
  - name: Copy a "sudoers" file on the remote machine for editing
    copy:
      src: /tmp/coffee-shop-html-template/
      dest: /var/www/html/
      remote_src: yes
